#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
Name     : compat-readline-soname5
Version  : 5.2
Release  : 4
URL      : https://ftp.gnu.org/gnu/readline/readline-5.2.tar.gz
Source0  : https://ftp.gnu.org/gnu/readline/readline-5.2.tar.gz
Source99 : https://ftp.gnu.org/gnu/readline/readline-5.2.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: compat-readline-soname5-lib = %{version}-%{release}
Requires: compat-readline-soname5-license = %{version}-%{release}
BuildRequires : ncurses-dev

%description
Introduction
============
This is the Gnu Readline library, version 5.2.
The Readline library provides a set of functions for use by applications
that allow users to edit command lines as they are typed in.  Both
Emacs and vi editing modes are available.  The Readline library includes
additional functions to maintain a list of previously-entered command
lines, to recall and perhaps reedit those lines, and perform csh-like
history expansion on previous commands.

%package dev
Summary: dev components for the compat-readline-soname5 package.
Group: Development
Requires: compat-readline-soname5-lib = %{version}-%{release}
Provides: compat-readline-soname5-devel = %{version}-%{release}

%description dev
dev components for the compat-readline-soname5 package.


%package doc
Summary: doc components for the compat-readline-soname5 package.
Group: Documentation

%description doc
doc components for the compat-readline-soname5 package.


%package lib
Summary: lib components for the compat-readline-soname5 package.
Group: Libraries
Requires: compat-readline-soname5-license = %{version}-%{release}

%description lib
lib components for the compat-readline-soname5 package.


%package license
Summary: license components for the compat-readline-soname5 package.
Group: Default

%description license
license components for the compat-readline-soname5 package.


%prep
%setup -q -n readline-5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543249271
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1543249271
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-readline-soname5
cp COPYING %{buildroot}/usr/share/package-licenses/compat-readline-soname5/COPYING
%make_install
## install_append content
mv %{buildroot}/usr/include/readline  %{buildroot}/usr/include/readline5
mv %{buildroot}/usr/lib64/libhistory.so %{buildroot}/usr/lib64/libhistory5.so
mv %{buildroot}/usr/lib64/libreadline.so %{buildroot}/usr/lib64/libreadline5.so
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/share/man/man3/history.3
%exclude /usr/share/man/man3/readline.3
/usr/include/readline5/chardefs.h
/usr/include/readline5/history.h
/usr/include/readline5/keymaps.h
/usr/include/readline5/readline.h
/usr/include/readline5/rlconf.h
/usr/include/readline5/rlstdc.h
/usr/include/readline5/rltypedefs.h
/usr/include/readline5/tilde.h
/usr/lib64/libhistory5.so
/usr/lib64/libreadline5.so

%files doc
%defattr(0644,root,root,0755)
%exclude /usr/share/info/history.info
%exclude /usr/share/info/readline.info
%exclude /usr/share/info/rluserman.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhistory.so.5
/usr/lib64/libhistory.so.5.2
/usr/lib64/libreadline.so.5
/usr/lib64/libreadline.so.5.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-readline-soname5/COPYING
